@startuml
!pragma teoz true
!theme materia
skinparam style strictuml
participant Handler
participant Listener

create Handler
Listener    ->      Handler     : \tfork
& Listener  ->      Listener    :

@enduml
